### ISSUE TITLE
Failed to deploy a stack: gotify-telegram Pulling gotify-telegram Error pull access denied for gotify-telegram

### ISSUE THREAD

**Issue by noob34433** [Raniita/gotify-telegram#1]

**Comment by leolionart** [comment]
Same to me

**Comment by slavid** [comment]
I'd suggest just build the image locally since it does not exist anymore in Docker Hub (or you could build it and push it there) like for instance this is how the `docker-compose.yml` file would look like:

```
version: '3.7'

services:

  gotify-telegram:
#    image: gotify-telegram
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gotify-telegram
    restart: unless-stopped
    environment:
      - GOTIFY_URL=<URL>
      - GOTIFY_PORT=<HTTP PORT>
      - GOTIFY_CLIENT_TOKEN=<CLIENT TOKEN>
#      - GOTIFY_APP_TOKEN=<>
      - TELEGRAM_CHAT_ID=<TELEGRAM CHAT ID>
      - TELEGRAM_TOKEN=<TOKEN_HERE>
```
